name: DENV_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - minimap2>=2.17
  - python=3.9
  - pip=21.2.1
  - snakemake-minimal<=6.8.0
  - samtools<=1.11
  - bedtools 
  - bwa
  - ivar
  - nextalign
  - mafft