name: denv_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - matplotlib
  - numpy
  - python=3.9
  - samtools
  - bedtools
  - bwa
  - ivar
  - nextalign=2.11.0
  - mafft
  - snakemake-minimal