name: DENV_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - python=3.9
  - samtools
  - bedtools
  - bwa
  - ivar
  - nextalign
  - mafft
  - snakemake-minimal