name: test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - matplotlib
  - numpy
  - python=3.9
  - htslib=1.12
  - samtools=1.6
  - bedtools=2.30
  - bwa
  - ivar=1.3.1
  - nextalign
  - mafft
  - snakemake-minimal
  - openssl=1.1.1s
