name: denv_pipeline
on: [push, pull_request]
defaults:
  run:
    shell: bash -el {0}

jobs:
  run_pipeline_tests:
    name: analysis_pipeline test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: analysis_env
          channels: conda-forge,bioconda,defaults
          conda-version: "*"
      - name: install pipeline
        run: pip install -e .	
      - name: run_dry_run
        working-directory: tests
        run: denv_pipeline --config dry_run_config.yml --dry-run
      - name: test_setup
        working-directory: tests
        run: python unit_tests_dry_run.py 
              \--in-config dry_run_config.yml 
              \--out-config test_output_dry_run/output_config.yml
              \--outdir test_output_dry_run

      
